kind: Service
apiVersion: v1
metadata:
  name: foundation-agent
  namespace: {{ .AddonInstallNamespace }}
  labels:
    app: foundation-agent
spec:
  type: ClusterIP
  ports:
  - name: app
    port: 443
    protocol: TCP
    targetPort: 4443
  selector:
    app: foundation-agent